import os
import zipfile
import pandas as pd
import re
from bs4 import BeautifulSoup
import xml.etree.ElementTree as ET
from datetime import datetime, timedelta
import yfinance as yf
import warnings
import time
import shutil
warnings.filterwarnings('ignore')

class FixedMarketableSecuritiesExtractor:
    def __init__(self, xbrl_folder_path, downloads_path=None):
        self.xbrl_folder_path = xbrl_folder_path
        self.downloads_path = downloads_path
        self.results = []
        self.edinet_code_map = None
        self.processed_count = 0
        self.error_count = 0
        self.no_data_count = 0
        self.success_count = 0
        
        if downloads_path:
            self.load_edinet_code_map()
        
    def load_edinet_code_map(self):
        """EDINETコードマップを読み込み"""
        try:
            extracted_path = os.path.join(self.downloads_path, 'extracted')
            
            if os.path.exists(extracted_path):
                csv_files = [f for f in os.listdir(extracted_path) if f.endswith('.csv')]
                if csv_files:
                    csv_path = os.path.join(extracted_path, csv_files[0])
                    
                    # 複数のエンコーディングを試す
                    encodings = ['shift_jis', 'utf-8', 'cp932', 'euc-jp']
                    for encoding in encodings:\n",
    "                        try:\n",
    "                            self.edinet_code_map = pd.read_csv(csv_path, encoding=encoding)\n",
    "                            print(f\"EDINETコードマップを読み込みました: {len(self.edinet_code_map)} 企業\")\n",
    "                            break\n",
    "                        except UnicodeDecodeError:\n",
    "                            continue\n",
    "                            \n",
    "        except Exception as e:\n",
    "            print(f\"EDINETコードマップの読み込みに失敗: {e}\")\n",
    "            \n",
    "    def extract_company_info_from_filename(self, filename):\n",
    "        \"\"\"ファイル名から会社情報を抽出（修正版）\"\"\"\n",
    "        # 正規表現パターンを修正（バックスラッシュを正しく記述）\n",
    "        pattern = r'_([A-Z0-9]+)-(\\d+)_(\\d{4}-\\d{2}-\\d{2})_'\n",
    "        match = re.search(pattern, filename)\n",
    "        if match:\n",
    "            return {\n",
    "                'company_code': match.group(1),\n",
    "                'document_id': match.group(2),\n",
    "                'filing_date': match.group(3)\n",
    "            }\n",
    "        return None\n",
    "\n",
    "    def get_company_info_from_edinet(self, edinet_code):\n",
    "        \"\"\"EDINETコードから会社情報を取得\"\"\"\n",
    "        if self.edinet_code_map is not None:\n",
    "            try:\n",
    "                match = self.edinet_code_map[self.edinet_code_map['ＥＤＩＮＥＴコード'] == edinet_code]\n",
    "                if not match.empty:\n",
    "                    row = match.iloc[0]\n",
    "                    return {\n",
    "                        'company_name': row.get('提出者名', ''),\n",
    "                        'stock_code': str(row.get('証券コード', '')).strip() if pd.notna(row.get('証券コード')) else None\n",
    "                    }\n",
    "            except Exception as e:\n",
    "                print(f\"EDINETコード {edinet_code} の情報取得エラー: {e}\")\n",
    "        return {'company_name': None, 'stock_code': None}\n",
    "\n",
    "    def extract_stock_code_from_name(self, security_name):\n",
    "        \"\"\"銘柄名から株式コードを抽出\"\"\"\n",
    "        if not security_name:\n",
    "            return None\n",
    "            \n",
    "        # 銘柄名の中の数字を抽出（通常は4桁の証券コード）\n",
    "        code_pattern = r'[（(]?(\\d{4})[）)]?'\n",
    "        match = re.search(code_pattern, security_name)\n",
    "        if match:\n",
    "            return match.group(1)\n",
    "        \n",
    "        # EDINETコードマップから検索\n",
    "        if self.edinet_code_map is not None:\n",
    "            try:\n",
    "                clean_name = security_name.replace('㈱', '').replace('株式会社', '').replace('(株)', '')\n",
    "                clean_name = clean_name.replace('（', '').replace('）', '').replace('(', '').replace(')', '')\n",
    "                \n",
    "                matches = self.edinet_code_map[self.edinet_code_map['提出者名'].str.contains(clean_name, na=False)]\n",
    "                if not matches.empty:\n",
    "                    stock_code = matches.iloc[0]['証券コード']\n",
    "                    if pd.notna(stock_code) and str(stock_code).strip() != '':\n",
    "                        return str(stock_code).strip()\n",
    "            except Exception:\n",
    "                pass\n",
    "        \n",
    "        return None\n",
    "\n",
    "    def extract_xbrl_data(self, xbrl_file_path):\n",
    "        \"\"\"XBRLファイルから特定投資株式情報を抽出\"\"\"\n",
    "        try:\n",
    "            with open(xbrl_file_path, 'r', encoding='utf-8') as file:\n",
    "                content = file.read()\n",
    "                \n",
    "            soup = BeautifulSoup(content, 'lxml-xml')\n",
    "            \n",
    "            # 特定投資株式の情報を抽出\n",
    "            securities_data = []\n",
    "            \n",
    "            # 各種要素を抽出\n",
    "            name_elements = soup.find_all('ix:nonNumeric', {'name': re.compile(r'NameOfSecuritiesDetailsOfSpecifiedInvestment.*')})\n",
    "            shares_elements = soup.find_all('ix:nonFraction', {'name': re.compile(r'NumberOfSharesHeldDetailsOfSpecifiedInvestment.*')})\n",
    "            book_value_elements = soup.find_all('ix:nonFraction', {'name': re.compile(r'BookValueDetailsOfSpecifiedInvestment.*')})\n",
    "            purpose_elements = soup.find_all('ix:nonNumeric', {'name': re.compile(r'PurposeOfShareholding.*SpecifiedInvestment.*')})\n",
    "            \n",
    "            # データを整理\n",
    "            for name_elem in name_elements:\n",
    "                if name_elem.get_text(strip=True):\n",
    "                    contextRef = name_elem.get('contextRef', '')\n",
    "                    \n",
    "                    # 当事業年度のデータのみ抽出\n",
    "                    if 'CurrentYearInstant' in contextRef:\n",
    "                        row_match = re.search(r'Row(\\d+)Member', contextRef)\n",
    "                        if row_match:\n",
    "                            row_num = row_match.group(1)\n",
    "                            \n",
    "                            # 対応するデータを検索\n",
    "                            current_shares = None\n",
    "                            current_book_value = None\n",
    "                            purpose = None\n",
    "                            \n",
    "                            # 株式数\n",
    "                            for shares_elem in shares_elements:\n",
    "                                if f'CurrentYearInstant_Row{row_num}Member' in shares_elem.get('contextRef', ''):\n",
    "                                    current_shares = shares_elem.get_text(strip=True).replace(',', '')\n",
    "                                    break\n",
    "                            \n",
    "                            # 貸借対照表計上額\n",
    "                            for book_elem in book_value_elements:\n",
    "                                if f'CurrentYearInstant_Row{row_num}Member' in book_elem.get('contextRef', ''):\n",
    "                                    current_book_value = book_elem.get_text(strip=True).replace(',', '')\n",
    "                                    break\n",
    "                            \n",
    "                            # 保有目的\n",
    "                            for purpose_elem in purpose_elements:\n",
    "                                if f'CurrentYearInstant_Row{row_num}Member' in purpose_elem.get('contextRef', ''):\n",
    "                                    purpose = purpose_elem.get_text(strip=True)\n",
    "                                    break\n",
    "                            \n",
    "                            if current_shares and current_book_value:\n",
    "                                try:\n",
    "                                    shares_val = int(current_shares) if current_shares.isdigit() else current_shares\n",
    "                                    book_val = float(current_book_value) if current_book_value.replace('.', '').isdigit() else current_book_value\n",
    "                                    \n",
    "                                    securities_data.append({\n",
    "                                        'security_name': name_elem.get_text(strip=True),\n",
    "                                        'shares': shares_val,\n",
    "                                        'book_value_million_yen': book_val,\n",
    "                                        'purpose': purpose if purpose else 'N/A'\n",
    "                                    })\n",
    "                                except ValueError:\n",
    "                                    # 数値変換エラーの場合はスキップ\n",
    "                                    continue\n",
    "            \n",
    "            return securities_data\n",
    "            \n",
    "        except Exception as e:\n",
    "            print(f\"XBRLファイル処理エラー {xbrl_file_path}: {str(e)}\")\n",
    "            return []\n",
    "\n",
    "    def extract_company_fundamentals(self, security_name, max_retries=2):\n",
    "        \"\"\"Yahoo Finance APIを使用してファンダメンタルズ情報を取得（簡素化版）\"\"\"\n",
    "        try:\n",
    "            # 株式コードを取得\n",
    "            stock_code = self.extract_stock_code_from_name(security_name)\n",
    "            \n",
    "            if stock_code:\n",
    "                ticker = f\"{stock_code}.T\"\n",
    "                \n",
    "                for attempt in range(max_retries):\n",
    "                    try:\n",
    "                        stock = yf.Ticker(ticker)\n",
    "                        info = stock.info\n",
    "                        \n",
    "                        # 現在の株価情報を取得\n",
    "                        hist = stock.history(period=\"1d\")\n",
    "                        current_price = hist['Close'].iloc[-1] if not hist.empty else None\n",
    "                        \n",
    "                        return {\n",
    "                            'ticker': ticker,\n",
    "                            'stock_code': stock_code,\n",
    "                            'current_price': current_price,\n",
    "                            'market_cap': info.get('marketCap'),\n",
    "                            'sector': info.get('sector'),\n",
    "                            'industry': info.get('industry')\n",
    "                        }\n",
    "                        \n",
    "                    except Exception:\n",
    "                        if attempt < max_retries - 1:\n",
    "                            time.sleep(0.5)\n",
    "                            continue\n",
    "                        else:\n",
    "                            break\n",
    "                            \n",
    "            return {'ticker': None, 'stock_code': stock_code}\n",
    "            \n",
    "        except Exception:\n",
    "            return {'ticker': None, 'stock_code': None}\n",
    "\n",
    "    def process_xbrl_folder(self, folder_path):\n",
    "        \"\"\"個別のXBRLフォルダを処理\"\"\"\n",
    "        try:\n",
    "            zip_files = [f for f in os.listdir(folder_path) if f.endswith('.zip')]\n",
    "            \n",
    "            if not zip_files:\n",
    "                return\n",
    "                \n",
    "            for zip_file in zip_files:\n",
    "                zip_path = os.path.join(folder_path, zip_file)\n",
    "                extract_path = os.path.join(folder_path, 'temp_extracted')\n",
    "                \n",
    "                try:\n",
    "                    # ZIPファイルを解凍\n",
    "                    with zipfile.ZipFile(zip_path, 'r') as zip_ref:\n",
    "                        zip_ref.extractall(extract_path)\n",
    "                    \n",
    "                    # 0104010_honbun ファイルを探す\n",
    "                    target_files = []\n",
    "                    for root, dirs, files in os.walk(extract_path):\n",
    "                        for file in files:\n",
    "                            if file.endswith('_ixbrl.htm') and '0104010_honbun' in file:\n",
    "                                target_files.append(os.path.join(root, file))\n",
    "                    \n",
    "                    if not target_files:\n",
    "                        self.no_data_count += 1\n",
    "                        if os.path.exists(extract_path):\n",
    "                            shutil.rmtree(extract_path)\n",
    "                        continue\n",
    "                    \n",
    "                    # 解凍されたファイルから情報を抽出\n",
    "                    for target_file in target_files:\n",
    "                        filename = os.path.basename(target_file)\n",
    "                        \n",
    "                        # ファイル名から会社情報を抽出\n",
    "                        company_info = self.extract_company_info_from_filename(filename)\n",
    "                        \n",
    "                        if company_info:\n",
    "                            # 会社情報を取得\n",
    "                            edinet_info = self.get_company_info_from_edinet(company_info['company_code'])\n",
    "                            \n",
    "                            # XBRLから特定投資株式情報を抽出\n",
    "                            securities_data = self.extract_xbrl_data(target_file)\n",
    "                            \n",
    "                            if securities_data:\n",
    "                                self.success_count += 1\n",
    "                                \n",
    "                                for security in securities_data:\n",
    "                                    # ファンダメンタルズ情報を取得\n",
    "                                    fundamentals = self.extract_company_fundamentals(security['security_name'])\n",
    "                                    \n",
    "                                    result = {\n",
    "                                        'filing_company_code': company_info['company_code'],\n",
    "                                        'filing_company_name': edinet_info['company_name'],\n",
    "                                        'filing_stock_code': edinet_info['stock_code'],\n",
    "                                        'filing_date': company_info['filing_date'],\n",
    "                                        'document_id': company_info['document_id'],\n",
    "                                        'held_security_name': security['security_name'],\n",
    "                                        'held_stock_code': fundamentals.get('stock_code'),\n",
    "                                        'held_shares': security['shares'],\n",
    "                                        'book_value_million_yen': security['book_value_million_yen'],\n",
    "                                        'holding_purpose': security['purpose'],\n",
    "                                        **fundamentals\n",
    "                                    }\n",
    "                                    \n",
    "                                    self.results.append(result)\n",
    "                            else:\n",
    "                                self.no_data_count += 1\n",
    "                    \n",
    "                    # 一時ファイルを削除\n",
    "                    if os.path.exists(extract_path):\n",
    "                        shutil.rmtree(extract_path)\n",
    "                        \n",
    "                    self.processed_count += 1\n",
    "                        \n",
    "                except Exception as e:\n",
    "                    print(f\"ZIPファイル処理エラー {zip_file}: {str(e)}\")\n",
    "                    self.error_count += 1\n",
    "                    if os.path.exists(extract_path):\n",
    "                        shutil.rmtree(extract_path)\n",
    "                        \n",
    "        except Exception as e:\n",
    "            print(f\"フォルダ処理エラー {folder_path}: {str(e)}\")\n",
    "            self.error_count += 1\n",
    "\n",
    "    def process_all_folders(self, limit=None):\n",
    "        \"\"\"すべてのXBRLフォルダを処理\"\"\"\n",
    "        folders = [f for f in os.listdir(self.xbrl_folder_path) \n",
    "                  if os.path.isdir(os.path.join(self.xbrl_folder_path, f))\n",
    "                  and not f.startswith('.')]\n",
    "        \n",
    "        if limit:\n",
    "            folders = folders[:limit]\n",
    "        \n",
    "        print(f\"処理対象フォルダ数: {len(folders)}\")\n",
    "        \n",
    "        for i, folder in enumerate(folders):\n",
    "            if i % 100 == 0:\n",
    "                print(f\"進捗: {i}/{len(folders)} - 成功: {self.success_count}, データなし: {self.no_data_count}, エラー: {self.error_count}\")\n",
    "            \n",
    "            folder_path = os.path.join(self.xbrl_folder_path, folder)\n",
    "            self.process_xbrl_folder(folder_path)\n",
    "            \n",
    "            # 適度な間隔でAPI制限を回避\n",
    "            if i > 0 and i % 50 == 0:\n",
    "                time.sleep(3)\n",
    "        \n",
    "        print(f\"\\n処理完了: {len(folders)} フォルダ\")\n",
    "        print(f\"成功: {self.success_count} 企業\")\n",
    "        print(f\"特定投資株式データなし: {self.no_data_count} 企業\")\n",
    "        print(f\"エラー: {self.error_count} 企業\")\n",
    "        print(f\"抽出データ件数: {len(self.results)}\")\n",
    "\n",
    "    def to_dataframe(self):\n",
    "        \"\"\"結果をDataFrameに変換\"\"\"\n",
    "        if not self.results:\n",
    "            return pd.DataFrame()\n",
    "        \n",
    "        df = pd.DataFrame(self.results)\n",
    "        return df\n",
    "\n",
    "    def save_to_csv(self, filename):\n",
    "        \"\"\"結果をCSVファイルに保存\"\"\"\n",
    "        df = self.to_dataframe()\n",
    "        if not df.empty:\n",
    "            df.to_csv(filename, index=False, encoding='utf-8-sig')\n",
    "            print(f\"データを保存しました: {filename}\")\n",
    "            print(f\"総レコード数: {len(df)}\")\n",
    "            print(f\"提出企業数: {df['filing_company_code'].nunique()}\")\n",
    "            return True\n",
    "        else:\n",
    "            print(\"保存するデータがありません。\")\n",
    "            return False\n",
    "\n",
    "def main():\n",
    "    # XBRLフォルダのパスを指定\n",
    "    xbrl_folder_path = \"/Users/satoki252595/work/0000_kabulab/0001_MarketableSecuritiesAnalysis/xbrl\"\n",
    "    downloads_path = \"/Users/satoki252595/work/0000_kabulab/0001_MarketableSecuritiesAnalysis/downloads\"\n",
    "    \n",
    "    # 修正版抽出器を初期化\n",
    "    extractor = FixedMarketableSecuritiesExtractor(xbrl_folder_path, downloads_path)\n",
    "    \n",
    "    # 全フォルダを処理（テスト用に500フォルダに制限）\n",
    "    extractor.process_all_folders(limit=500)\n",
    "    \n",
    "    # 結果をCSVに保存\n",
    "    extractor.save_to_csv('fixed_marketable_securities_analysis.csv')\n",
    "    \n",
    "    # 結果を表示\n",
    "    df = extractor.to_dataframe()\n",
    "    if not df.empty:\n",
    "        print(\"\\n=== 結果サマリー ===\")\n",
    "        print(df.head())\n",
    "        print(f\"\\n提出企業数: {df['filing_company_code'].nunique()}\")\n",
    "        print(f\"保有銘柄数: {df['held_security_name'].nunique()}\")\n",
    "        print(f\"株式コード取得済み: {df['held_stock_code'].notna().sum()}\")\n",
    "\n",
    "if __name__ == \"__main__\":\n",
    "    main()"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## 1. セットアップ"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# 必要なライブラリのインポート\n",
    "import sys\n",
    "import os\n",
    "import pandas as pd\n",
    "import warnings\n",
    "warnings.filterwarnings('ignore')\n",
    "\n",
    "# 修正版スクリプトをインポート\n",
    "sys.path.append('/Users/satoki252595/work/0000_kabulab/0001_MarketableSecuritiesAnalysis')\n",
    "from fixed_extraction import FixedMarketableSecuritiesExtractor\n",
    "\n",
    "print(\"セットアップ完了\")"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## 2. 全データ処理実行"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# 設定\n",
    "XBRL_FOLDER_PATH = \"/Users/satoki252595/work/0000_kabulab/0001_MarketableSecuritiesAnalysis/xbrl\"\n",
    "DOWNLOADS_PATH = \"/Users/satoki252595/work/0000_kabulab/0001_MarketableSecuritiesAnalysis/downloads\"\n",
    "PROCESS_LIMIT = 1000  # 処理するフォルダ数の制限（None で全て処理）\n",
    "\n",
    "# 修正版抽出器を初期化\n",
    "extractor = FixedMarketableSecuritiesExtractor(XBRL_FOLDER_PATH, DOWNLOADS_PATH)\n",
    "\n",
    "# 全データ処理を実行\n",
    "print(\"全データ処理を開始します...\")\n",
    "extractor.process_all_folders(limit=PROCESS_LIMIT)\n",
    "\n",
    "# 結果をDataFrameに変換\n",
    "df = extractor.to_dataframe()\n",
    "\n",
    "print(f\"\\n=== 処理結果 ===\")\n",
    "print(f\"抽出データ件数: {len(df)}\")\n",
    "if not df.empty:\n",
    "    print(f\"提出企業数: {df['filing_company_code'].nunique()}\")\n",
    "    print(f\"保有銘柄数: {df['held_security_name'].nunique()}\")\n",
    "    print(f\"株式コード取得済み: {df['held_stock_code'].notna().sum()}\")"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## 3. 結果の確認と分析"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "if not df.empty:\n",
    "    print(\"=== データサンプル ===\")\n",
    "    display(df[['filing_company_code', 'filing_company_name', 'held_security_name', 'held_shares', 'book_value_million_yen']].head(10))\n",
    "    \n",
    "    print(\"\\n=== 提出企業の分析 ===\")\n",
    "    filing_companies = df['filing_company_code'].value_counts().head(10)\n",
    "    print(\"保有銘柄数が多い企業:\")\n",
    "    for company_code, count in filing_companies.items():\n",
    "        company_name = df[df['filing_company_code'] == company_code]['filing_company_name'].iloc[0]\n",
    "        print(f\"{company_code} ({company_name}): {count} 銘柄\")\n",
    "    \n",
    "    print(\"\\n=== 最も多く保有されている銘柄 ===\")\n",
    "    most_held = df['held_security_name'].value_counts().head(10)\n",
    "    for security, count in most_held.items():\n",
    "        print(f\"{security}: {count} 社が保有\")\n",
    "    \n",
    "    print(\"\\n=== 貸借対照表計上額の統計 ===\")\n",
    "    print(df['book_value_million_yen'].describe())\n",
    "else:\n",
    "    print(\"データが抽出されませんでした。\")"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## 4. 時価総額比率の計算"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# 時価総額比率の計算を市場価格データを使用せずに貸借対照表計上額で計算\n",
    "if not df.empty:\n",
    "    # 企業別の保有株式合計額を計算\n",
    "    holdings_summary = df.groupby(['filing_company_code', 'filing_company_name', 'filing_stock_code']).agg({\n",
    "        'book_value_million_yen': 'sum',\n",
    "        'held_security_name': 'count'\n",
    "    }).reset_index()\n",
    "    \n",
    "    holdings_summary.columns = ['filing_company_code', 'filing_company_name', 'filing_stock_code', \n",
    "                               'total_holdings_book_value', 'holdings_count']\n",
    "    \n",
    "    # 保有株式額が大きい企業順に表示\n",
    "    holdings_summary = holdings_summary.sort_values('total_holdings_book_value', ascending=False)\n",
    "    \n",
    "    print(\"=== 保有株式簿価総額 上位20社 ===\")\n",
    "    display_summary = holdings_summary.head(20).copy()\n",
    "    display_summary['total_holdings_book_value_billion'] = display_summary['total_holdings_book_value'] / 1000\n",
    "    \n",
    "    display_cols = ['filing_company_name', 'filing_stock_code', 'total_holdings_book_value_billion', 'holdings_count']\n",
    "    display_df = display_summary[display_cols].copy()\n",
    "    display_df.columns = ['会社名', '証券コード', '保有株式簿価(十億円)', '保有銘柄数']\n",
    "    display_df['保有株式簿価(十億円)'] = display_df['保有株式簿価(十億円)'].round(2)\n",
    "    \n",
    "    display(display_df)\n",
    "    \n",
    "    # 保有銘柄数が多い企業\n",
    "    print(\"\\n=== 保有銘柄数 上位10社 ===\")\n",
    "    top_holdings_count = holdings_summary.nlargest(10, 'holdings_count')\n",
    "    for _, row in top_holdings_count.iterrows():\n",
    "        print(f\"{row['filing_company_name']} ({row['filing_stock_code']}): {row['holdings_count']} 銘柄, {row['total_holdings_book_value']:.0f} 百万円\")"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## 5. 結果保存"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# 結果をCSVに保存\n",
    "if not df.empty:\n",
    "    output_filename = f\"full_marketable_securities_analysis_{len(df)}records.csv\"\n",
    "    df.to_csv(output_filename, index=False, encoding='utf-8-sig')\n",
    "    \n",
    "    print(f\"全データを保存しました: {output_filename}\")\n",
    "    print(f\"ファイルサイズ: {os.path.getsize(output_filename) / 1024:.2f} KB\")\n",
    "    \n",
    "    # 企業別サマリーも保存\n",
    "    summary_filename = f\"companies_summary_{len(holdings_summary)}companies.csv\"\n",
    "    holdings_summary.to_csv(summary_filename, index=False, encoding='utf-8-sig')\n",
    "    print(f\"企業別サマリーを保存しました: {summary_filename}\")\n",
    "    \n",
    "    print(f\"\\n=== 最終統計 ===\")\n",
    "    print(f\"総レコード数: {len(df)}\")\n",
    "    print(f\"提出企業数: {df['filing_company_code'].nunique()}\")\n",
    "    print(f\"保有銘柄数: {df['held_security_name'].nunique()}\")\n",
    "    print(f\"処理成功企業数: {extractor.success_count}\")\n",
    "    print(f\"特定投資株式データなし企業数: {extractor.no_data_count}\")\n",
    "    print(f\"エラー企業数: {extractor.error_count}\")\n",
    "    print(f\"成功率: {extractor.success_count/(extractor.success_count + extractor.no_data_count + extractor.error_count)*100:.1f}%\")\n",
    "else:\n",
    "    print(\"保存するデータがありません。\")"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.8.5"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 4
}